Scikit-learn's GridSearchCV is capable of runing several combinations of hyperparameter values to find the best combination to attain the best performance of the model.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV

In [12]:
df = pd.read_csv('../../jupyter_notebooks/DATA/Advertising.csv')
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [13]:
X = df.drop('sales',axis=1)
y = df['sales']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=101)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
base_elastic_net_model = ElasticNet()

In [15]:
param_grid={'alpha':[0.1,1,5,10,50,100],'l1_ratio':[.1,.5,.7,.95,.99,1]}

In [16]:
grid_model=GridSearchCV(estimator = base_elastic_net_model,param_grid = param_grid, scoring='neg_mean_squared_error',cv=5,verbose=2)

In [17]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.1, l1_ratio=0.99; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=0.1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=1, l1_ratio=0.99; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=1, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END ..............................alpha=5, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.95; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END .............................alpha=5, l1_ratio=0.99; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END ................................alpha=5, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=10, l1_ratio=0.99; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=10, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END .............................alpha=50, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.95; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ............................alpha=50, l1_ratio=0.99; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ...............................alpha=50, l1_ratio=1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.95; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=100, l1_ratio=0.99; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s
[CV] END ..............................alpha=100, l1_ratio=1; total time=   0.0s

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [18]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [19]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [20]:
pd.DataFrame(grid_model.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002746,0.002208,0.001241,0.000653,0.1,0.10,"{'alpha': 0.1, 'l1_ratio': 0.1}",-3.453021,-1.405190,-5.789125,-2.187302,-4.645576,-3.496043,1.591601,6
1,0.001283,0.000200,0.000678,0.000057,0.1,0.50,"{'alpha': 0.1, 'l1_ratio': 0.5}",-3.325440,-1.427522,-5.595610,-2.163089,-4.451679,-3.392668,1.506827,5
2,0.001242,0.000143,0.000648,0.000152,0.1,0.70,"{'alpha': 0.1, 'l1_ratio': 0.7}",-3.269880,-1.442432,-5.502437,-2.163950,-4.356738,-3.347088,1.462765,4
3,0.001264,0.000127,0.000640,0.000081,0.1,0.95,"{'alpha': 0.1, 'l1_ratio': 0.95}",-3.213052,-1.472417,-5.396258,-2.177452,-4.241080,-3.300052,1.406248,3
4,0.001248,0.000239,0.000621,0.000068,0.1,0.99,"{'alpha': 0.1, 'l1_ratio': 0.99}",-3.208124,-1.478489,-5.380242,-2.181097,-4.222968,-3.294184,1.396953,2
5,0.001108,0.000119,0.000593,0.000119,0.1,1.00,"{'alpha': 0.1, 'l1_ratio': 1}",-3.206943,-1.480065,-5.376257,-2.182076,-4.218460,-3.292760,1.394613,1
6,0.001144,0.000155,0.000680,0.000116,1.0,0.10,"{'alpha': 1, 'l1_ratio': 0.1}",-9.827475,-5.261525,-11.875347,-7.449195,-8.542329,-8.591174,2.222939,12
7,0.001212,0.000288,0.000631,0.000109,1.0,0.50,"{'alpha': 1, 'l1_ratio': 0.5}",-8.707071,-4.214228,-10.879261,-6.204545,-7.173031,-7.435627,2.255532,11
8,0.001586,0.000192,0.000861,0.000207,1.0,0.70,"{'alpha': 1, 'l1_ratio': 0.7}",-7.920870,-3.549562,-10.024877,-5.379553,-6.324836,-6.639940,2.206213,10
9,0.000967,0.000063,0.000518,0.000032,1.0,0.95,"{'alpha': 1, 'l1_ratio': 0.95}",-6.729435,-2.591285,-8.709842,-4.156317,-5.329916,-5.503359,2.102835,9
10,0.001040,0.000171,0.000594,0.000132,1.0,0.99,"{'alpha': 1, 'l1_ratio': 0.99}",-6.521344,-2.431385,-8.471086,-3.946327,-5.151344,-5.304297,2.079945,8
11,0.000909,0.000015,0.000499,0.000028,1.0,1.00,"{'alpha': 1, 'l1_ratio': 1}",-6.468807,-2.391483,-8.410171,-3.893566,-5.105922,-5.253990,2.073832,7
12,0.001282,0.000271,0.000628,0.000068,5.0,0.10,"{'alpha': 5, 'l1_ratio': 0.1}",-22.979265,-15.547104,-23.668249,-19.921063,-16.262737,-19.675684,3.334901,13
13,0.001076,0.000047,0.000544,0.000040,5.0,0.50,"{'alpha': 5, 'l1_ratio': 0.5}",-27.793488,-18.602269,-27.107849,-23.945227,-18.064635,-23.102694,4.108297,14
14,0.001011,0.000011,0.000529,0.000007,5.0,0.70,"{'alpha': 5, 'l1_ratio': 0.7}",-29.655510,-21.085059,-29.629478,-26.724595,-20.223654,-25.463659,4.077877,16
15,0.000950,0.000053,0.000519,0.000044,5.0,0.95,"{'alpha': 5, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
16,0.000818,0.000031,0.000436,0.000019,5.0,0.99,"{'alpha': 5, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
17,0.000820,0.000025,0.000486,0.000059,5.0,1.00,"{'alpha': 5, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
18,0.001153,0.000525,0.000652,0.000277,10.0,0.10,"{'alpha': 10, 'l1_ratio': 0.1}",-27.385346,-19.159534,-27.635464,-24.154104,-18.968161,-23.460522,3.794608,15
19,0.001781,0.000602,0.000698,0.000205,10.0,0.50,"{'alpha': 10, 'l1_ratio': 0.5}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
20,0.001286,0.000248,0.000645,0.000145,10.0,0.70,"{'alpha': 10, 'l1_ratio': 0.7}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
21,0.001262,0.000288,0.000740,0.000216,10.0,0.95,"{'alpha': 10, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
22,0.001524,0.000058,0.000794,0.000221,10.0,0.99,"{'alpha': 10, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
23,0.001638,0.000089,0.000959,0.000124,10.0,1.00,"{'alpha': 10, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
24,0.001358,0.000182,0.000716,0.000139,50.0,0.10,"{'alpha': 50, 'l1_ratio': 0.1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
25,0.001266,0.000145,0.000628,0.000043,50.0,0.50,"{'alpha': 50, 'l1_ratio': 0.5}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
26,0.001295,0.000187,0.000705,0.000150,50.0,0.70,"{'alpha': 50, 'l1_ratio': 0.7}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
27,0.001612,0.000412,0.000810,0.000150,50.0,0.95,"{'alpha': 50, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
28,0.001740,0.000185,0.000880,0.000095,50.0,0.99,"{'alpha': 50, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
29,0.001685,0.000068,0.000888,0.000082,50.0,1.00,"{'alpha': 50, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
30,0.001623,0.000360,0.000685,0.000167,100.0,0.10,"{'alpha': 100, 'l1_ratio': 0.1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
31,0.001478,0.000362,0.001025,0.000101,100.0,0.50,"{'alpha': 100, 'l1_ratio': 0.5}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
32,0.001545,0.000335,0.000743,0.000171,100.0,0.70,"{'alpha': 100, 'l1_ratio': 0.7}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
33,0.001535,0.000392,0.000797,0.000319,100.0,0.95,"{'alpha': 100, 'l1_ratio': 0.95}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
34,0.001523,0.000316,0.000751,0.000186,100.0,0.99,"{'alpha': 100, 'l1_ratio': 0.99}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17
35,0.001757,0.000213,0.000778,0.000176,100.0,1.00,"{'alpha': 100, 'l1_ratio': 1}",-31.130307,-22.549433,-31.155204,-27.963447,-21.698192,-26.899317,4.077240,17

In [22]:
y_pred = grid_model.predict(X_test)

In [24]:
mean_squared_error(y_test,y_pred)

2.387342642087474