# Model Persistance with Scikit-Learn

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('../../jupyter_notebooks/DATA/Advertising.csv')

In [4]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
df.describe()

               TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [6]:
X=df.drop('sales',axis=1)
y=df['sales']

In [7]:
from sklearn.model_selection import train_test_split

You want to split into 3 sets: train, validation and hold out.

First split will be train/rest; may be 70-30%

Second sprint will be dividing the rest (the 30% of the total) into test/hold out, may be in equal parts (50-50%) or more to validation if data is scarse.

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [9]:
X_validation, X_holdout_test, y_validation, y_hold_out_test = train_test_split(X_test, y_test, test_size=0.5, random_state=101)

In [10]:
len(X_train)

140

In [11]:
len(X)

200

In [12]:
len(X_holdout_test)

30

In [13]:
len(X_validation)

30

## Model Training

In [14]:
from sklearn.ensemble import RandomForestRegressor

In [15]:
model=RandomForestRegressor(n_estimators=3,random_state=101)

In [16]:
model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=3, random_state=101)

In [17]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [18]:
validation_predictions=model.predict(X_validation)

In [19]:
mean_absolute_error(y_validation,validation_predictions)

0.853333333333333

In [20]:
mean_squared_error(y_validation,validation_predictions)**0.5

1.1031268688998959

In [21]:
df.describe()['sales']

count    200.000000
mean      14.022500
std        5.217457
min        1.600000
25%       10.375000
50%       12.900000
75%       17.400000
max       27.000000
Name: sales, dtype: float64

Let's assume that we are not satisfied with the result (let's tune some hyperparameters)

In [22]:
model30=RandomForestRegressor(n_estimators=30,random_state=101)

In [24]:
model30.fit(X_train,y_train)

RandomForestRegressor(n_estimators=30, random_state=101)

In [25]:
validation_predictions30=model30.predict(X_validation)

In [26]:
mean_absolute_error(y_validation,validation_predictions30)

0.6575555555555552

From 0.85333 with 3 estimators, we have gone down to 0.657555 with 30.

In [27]:
mean_squared_error(y_validation,validation_predictions30)**0.5

0.8542009478215644

From 1.103127 we have gone down to 0.85420

We have improved and, let's say we are satisfied. We have to check the model with data it has not seen: hold out set. This is going to be how the model is going to perform in real world with unseen data.

### Final performance metrics

In [28]:
holdout_predictions=model30.predict(X_holdout_test)

In [29]:
mean_absolute_error(y_hold_out_test,holdout_predictions)

0.5937777777777775

In [30]:
mean_squared_error(y_hold_out_test,holdout_predictions)**0.5

0.745323693040418

In [31]:
final_model=RandomForestRegressor(n_estimators=30,random_state=101)

In [32]:
final_model.fit(X,y)

RandomForestRegressor(n_estimators=30, random_state=101)

In [33]:
import joblib

In [34]:
# save the model, so can be reused.
joblib.dump(final_model,'final_model.pkl')

['final_model.pkl']

You should also save the columns from your training data, in the order you used them to train the model

In [35]:
list(X.columns)

['TV', 'radio', 'newspaper']

In [36]:
joblib.dump(list(X.columns),'col_names.pkl')

['col_names.pkl']

## Test the saved model
Now let's check that we can use the model from the files we just saved.

In [37]:
new_columns = joblib.load('col_names.pkl')

In [39]:
new_columns

['TV', 'radio', 'newspaper']

In [40]:
loaded_model=joblib.load('final_model.pkl')

In [41]:
loaded_model.predict([[230.1,37.8,69.2]])

C:\Users\mvgarcia\.conda\envs\PythonMLandDS\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([21.99])

That is actually quite close to the original value (22.1) of the first row of data, that we just used.

# Making the model available to anyone
Now that the model is persisted, what we need is some way to provide it as an API or available service that anyone can use to predict with new data.

We are going to wrap the ML model with a Flask library for python.

Then one can POST new data and then GET the results of predicting with the model the result for that new data.